# Generated by Django 5.2.1 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
